[tool.briefcase.app.myapp]
formal_name = "MyApp"
description = "An awesome cross-platform app built with Python"
author = "Fatemeh Heydarian"
author_email = "heydarianfatemeh9014@gmail.com"
license = "MIT"
url = "https://github.com/heydarianfatemeh9014/school_8th_help_version3_main2"


[tool.briefcase.app.MyApp]
sources = ["codes"]
icon = "imagess/icon.png"
