[tool.briefcase.app.myapp]
formal_name = "MyApp"
description = "An awesome cross-platform app built with Python"
author = "Fatemeh Heydarian"
author_email = "heydarianfatemeh9014@gmail.com"
license = "MIT"
url = "https://github.com/heydarianfatemeh9014/school_8th_help_version3_main2"
sources = ["codes"]
icon = "imagess/icon.png"

[tool.briefcase.app.myapp.android]
package = "com.fatemeh.myapp"
version = "0.1.0"
requirements = ["python3", "tkinter", "Pillow"]
sdk_min = 21
sdk_target = 33
orientation = "portrait"
