name: Build APK with Briefcase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Build Android APK
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my_python_app
          path: "android/*/build/outputs/apk/debug/*.apk"
