name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
            libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev libunwind-dev zlib1g-dev \
            libsqlite3-dev sqlite3 bzip2 libbz2-dev openssl libgdbm-dev libgdbm-compat-dev liblzma-dev \
            libreadline-dev uuid-dev libgstreamer-plugins-base1.0-0 gstreamer1.0-plugins-good \
            zip unzip autoconf libtool pkg-config libncurses5-dev libncursesw5-dev cmake \
            libffi-dev libssl-dev automake default-jdk

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade buildozer cython==0.29.33 git+https://github.com/kivy/plyer.git

      - name: Ensure Buildozer directories
        run: |
          mkdir -p $HOME/.buildozer
          mkdir -p $GITHUB_WORKSPACE/.buildozer

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: school_apk
          path: $GITHUB_WORKSPACE/bin/*.apk
          retention-days: 3
