name: Build and Upload APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase==0.3.25

      - name: Build Android APK
        run: |
          # ایجاد پروژه اندروید با Briefcase
          briefcase create android
          briefcase build android
          briefcase package android

      - name: List APK file (for debugging)
        run: |
          ls -R build/android/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: school-apk
          path: build/android/*/outputs/apk/debug/*.apk
          if-no-files-found: error
          retention-days: 3
