name: Build and Upload APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk git unzip wget curl

      - name: Install Briefcase
        run: |
          pip install --upgrade pip
          pip install briefcase==0.3.25

      - name: Build APK with Briefcase
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: List APKs (for debug)
        run: ls -R school/build/android/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: school_apk
          path: school/build/android/gradle/outputs/apk/debug/*.apk
          retention-days: 3
