name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - uses: actions/checkout@v4

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Setup Java 17 for Gradle
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Install Linux dependencies
      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git ffmpeg libsdl2-dev libsdl2-image-dev \
          libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev \
          libavcodec-dev libunwind-dev zlib1g-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev \
          openssl libgdbm-dev libgdbm-compat-dev liblzma-dev libreadline-dev uuid-dev \
          libgstreamer1.0-0 libgstreamer1.0-dev gstreamer1.0-plugins-base \
          gstreamer1.0-plugins-good zip unzip autoconf libtool pkg-config libncurses5-dev \
          libncursesw5-dev cmake libffi-dev libssl-dev automake

      # Install Python packages
      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 git+https://github.com/kivy/plyer.git

      # Clean previous build
      - name: Clean previous build
        run: |
          rm -rf .buildozer bin

      # Build APK
      - name: Build APK
        run: |
          buildozer android debug android_arch=arm64-v8a

      # Upload APK artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: school_apk
          path: bin/*.apk
          retention-days: 3
