name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase
        # مطمئن شو pywin32 و Kivy Windows-only از requirements.txt حذف شدند
        pip install -r requirements.txt

    - name: Build Android APK
      run: |
        briefcase create android
        briefcase build android
        briefcase package android

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: School_8th_help
        path: android/MyApp/build/android/MyApp-debug.apk
