name: Build APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3-pip python3-dev build-essential git \
            zip unzip zlib1g-dev libncurses5-dev libncursesw5-dev \
            libreadline-dev libsqlite3-dev libssl-dev libgdbm-dev \
            libbz2-dev libffi-dev liblzma-dev wget curl openjdk-17-jdk \
            libjpeg-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev \
            libsdl2-ttf-dev libportmidi-dev ffmpeg libswscale-dev \
            libavformat-dev libavcodec-dev cmake automake autoconf libtool pkg-config

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Buildozer & Cython
        run: |
          python3 -m pip install --upgrade pip
          pip install buildozer cython==0.29.33 git+https://github.com/kivy/plyer.git

      - name: Download Android SDK Command Line Tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip sdk-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Build APK
        run: |
          buildozer android debug
          ls -lh bin/

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: school_apk
          path: bin/*.apk
          retention-days: 3
