name: Build and Upload APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-17-jdk git wget unzip curl

      - name: Install Briefcase
        run: pip install briefcase==0.3.25

      - name: Build Android APK
        run: |
          briefcase create android
          briefcase build android
          briefcase package android

      - name: Locate APK
        id: find_apk
        run: |
          APK=$(find ./school/build/android/ -type f -name "*.apk" | head -n 1)
          if [ -z "$APK" ]; then
            echo "No APK found, exiting..."
            exit 1
          fi
          echo "apk_path=$APK" >> $GITHUB_ENV
      
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: school-apk
          path: ${{ env.apk_path }}
          retention-days: 3
